#!/usr/bin/env php
<?php

namespace Siesta\Console;

require_once 'vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new ReverseCommand('reverse'));
$app->add(new GeneratorCommand('gen'));
$app->add(new InitCommand('init'));

$app->run();