CREATE
  PROCEDURE `SIESTA_GET_COLUMN_DETAILS`(IN P_SCHEMA_NAME VARCHAR(64), IN P_TABLE_NAME VARCHAR(64))
  NOT DETERMINISTIC MODIFIES SQL DATA SQL SECURITY INVOKER
BEGIN
  SELECT
    *
	FROM
	  information_schema.COLUMNS
  WHERE
    TABLE_SCHEMA = P_SCHEMA_NAME AND
    TABLE_NAME = P_TABLE_NAME;
END