CREATE PROCEDURE

  `SIESTA_GET_FOREIGN_KEY_DETAILS` (IN P_SCHEMA_NAME VARCHAR(64), IN P_TABLE_NAME VARCHAR(64))

	NOT DETERMINISTIC READS SQL DATA SQL SECURITY INVOKER

BEGIN
	SELECT
		KC.COLUMN_NAME,
		KC.CONSTRAINT_NAME,
		KC.REFERENCED_TABLE_NAME,
		KC.REFERENCED_COLUMN_NAME,
		RC.DELETE_RULE,
		RC.UPDATE_RULE

	FROM
		information_schema.key_column_usage as KC,
		information_schema.REFERENTIAL_CONSTRAINTS AS RC

	WHERE
		KC.REFERENCED_TABLE_NAME IS NOT NULL AND
		KC.TABLE_NAME = P_TABLE_NAME AND
		KC.CONSTRAINT_SCHEMA = P_SCHEMA_NAME AND
		RC.CONSTRAINT_NAME = KC.CONSTRAINT_NAME AND
		RC.TABLE_NAME = P_TABLE_NAME AND
		RC.CONSTRAINT_SCHEMA = P_SCHEMA_NAME;

END