CREATE PROCEDURE

  `SIESTA_GET_INDEX_DETAILS` (IN P_SCHEMA_NAME VARCHAR(64), IN P_TABLE_NAME VARCHAR(64))

	NOT DETERMINISTIC READS SQL DATA SQL SECURITY INVOKER

BEGIN

  SELECT
      S.*
  FROM
    INFORMATION_SCHEMA.STATISTICS AS S
  WHERE
    S.TABLE_NAME = P_TABLE_NAME AND
    S.TABLE_SCHEMA = P_SCHEMA_NAME;
END